### PR TITLE
Allow overriding default mappings

### LINKED ISSUE #26: Disable default mappings
Please add the ability to disable default mappings.
Since Ctrl-K for me is mapped to cycle through telescope history, but telescope-live-grep-args forces its behaviour...
```
local default_mappings = {
  i = {
    ["<C-k>"] = actions.quote_prompt(), -- k for kwote :D - q is already taken
    ["<C-l>g"] = actions.quote_prompt({ postfix = ' --iglob ' }), -- l for live grep args; g for glob
    ["<C-l>t"] = actions.quote_prompt({ postfix = ' -t' }), -- l for live grep args; t for type
  },
}

local live_grep_args = function(opts)
  opts = vim.tbl_extend("force", setup_opts, opts or {})
  opts.mappings = vim.tbl_deep_extend("force", default_mappings, opts.mappings or {})
```

### PR DESCRIPTION
**Pull request by weeman1337**
- Add `default_mappings` option
- Adds section about mappings to the README

Closes #26

### CODE REVIEW

**Review by steliyan — APPROVED** [review]
A great escape hatch. :)

**Comment by weeman1337** [comment]
Thanks for your feedback @steliyan .

I crawled the Telescope code and found that there is another option that allows you to override the defaults: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua#L130 . I tend to build it the same way.

**Comment by weeman1337** [comment]
Ok, convinced :laughing: Will update the PR

**Comment by weeman1337** [comment]
@steliyan default shortcuts are gone. Can you give it a try?

**Comment by steliyan** [comment]
Works as expected! :)

**Comment by weeman1337** [comment]
> Also, default_mapping usage is discouraged in Telescope.

@steliyan can you give me a hint to the code / doc mentioning this?

I am not yet finally decided.

**Comment by steliyan** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L368

**Comment by weeman1337** [comment]
> Not recommended to use except for advanced users.

That is exactly what we are looking for I think :wink: - „advanced uses“

**Comment by weeman1337** [comment]
@steliyan another update :wink: 

Similar to Telescope I am going to add `default_mappings` for power users.

**Comment by steliyan** [comment]
This works! ;)
But as I already mentioned, it doesn't work as an extension option, you need to pass it to the `live_grep_args` instance.

This works:
```lua
require('telescope').extensions.live_grep_args.live_grep_args({
    default_mappings = {
      i = {
        ['<C-r>'] = semi_quote({ prefix = '--no-fixed-strings ' }),
      },
    },
  })
```

This does not work:
```lua
require('telescope').setup({
  extensions = {
    live_grep_args = {
      default_mappings = {
        ['<C-r>'] = semi_quote({ prefix = '--no-fixed-strings ' }),
      }
    }
  }
})
```

**Review by steliyan — APPROVED** [review]

**Comment by weeman1337** [comment]
> This does not work:
> 
> ```lua
> require('telescope').setup({
>   extensions = {
>     live_grep_args = {
>       default_mappings = {
>         ['<C-r>'] = semi_quote({ prefix = '--no-fixed-strings ' }),
>       }
>     }
>   }
> })
> ```

It should be 
```lua
extensions = {
  live_grep_args = {
    default_mappings = {
        i = {
          ['<C-r>'] = semi_quote({ prefix = '--no-fixed-strings ' }),
        },
    },
}
 ```

Tested and works on my machine™

Can you have another look @steliyan ?

**Comment by steliyan** [comment]
I'd never added the `load_extensions('live_grep_args')` to my config. 😵‍💫 
It works as expected, sorry for misleading you...

**Comment by steliyan** [comment]
@weeman1337 is something blocking this? I say it's ready for the public (read `master` branch). :)

**Comment by weeman1337** [comment]
> @weeman1337 is something blocking this? I say it's ready for the public (read `master` branch). :)

I am always testing around for a while :wink: But yes, it seems to be working fine. Going to merge it in the afternoon.

**Pull request merged**
